"""added posts

Revision ID: 663d50c71775
Revises: a4f5ee71355a
Create Date: 2023-01-18 22:18:35.501700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663d50c71775'
down_revision = 'a4f5ee71355a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=30), server_default='', nullable=False),
    sa.Column('Text', sa.String(length=350), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_model')
    # ### end Alembic commands ###