# Generated by Django 4.1.7 on 2023-02-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_songs_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
