name: Django CI

on:
  push:
    branches: [ "homework_2", "master" ]
  pull_request:
    branches: [ "homework_2", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd homework_10 
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd homework_10/MuzClub
        python manage.py test
